### ISSUE TITLE
Update firmware links on OXRS.IO

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-LEDController-ESP-FW#7]
Links in the table [here](https://oxrs.io/docs/hardware/output-devices/pwm-controllers.html#choose-your-adventure) are pointing to the old repos. Need to be updated to point to this new combined repo.

**Comment by austinscreations** [comment]
pending github PR

**Comment by austinscreations** [comment]
pr approved (https://github.com/OXRS-IO/OXRS-IO-WEBSITE/pull/48)
